baseURL = 'https://BuzzookaDev.github.io/affiliate-site/'
languageCode = 'en-us'
title = 'BuzzookaDev Affiliate Reviews'
theme = 'ananke'

[params]
  description = "Expert reviews on ergonomic workspace gear."
