baseURL = 'https://buzzookadev.github.io/affiliate-site/'
languageCode = 'en-us'
title = 'BuzzookaDev Affiliate Reviews'
theme = 'ananke'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "Expert reviews on ergonomic workspace gear."
  recent_posts_number = 10
  mainSections = ["posts"]

[[menu.main]]
  name = "Reviews"
  url = "/posts/"
  weight = 10
